name: ci-build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python }}
      - name: Sync test environment
        run: uv sync --group test
      - name: Run tests
        run: uv run pytest tests -v --tb=short
      - name: Build
        run: uv build

  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
      - name: Install dependencies
        run: |
            uv venv
            uv pip install -r doc/requirements.txt
            uv pip install .
      - name: Build and check docs
        run: uv run --no-sync make -C doc check SPHINXOPTS="-W --keep-going"
