name: ci-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install build
      - name: Install reki
        run: |
            python -m pip install -e .
      - name: Install test dependencies
        run: |
            python -m pip install --group test
      - name: Run tests
        run: |
            python -m pytest tests -v --tb=short
      - name: Build
        run: |
            python -m build

  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r doc/requirements.txt
            python -m pip install .
      - name: Download test data
        run: |
            make -C doc data
      - name: Build docs
        run: |
            make -C doc html